import type {
  Cliente,
  ContaPagar,
  EventoCalendario,
  Ingrediente,
  Material,
  MovimentoCaixa,
  Pedido,
  Perda,
  Produto,
} from "./types";

export const clientes: Cliente[] = [
  {
    id: "c1",
    nome: "Maria José",
    telefone: "+258 84 123 4567",
    endereco: "Av. Julius Nyerere, Maputo",
  },
  {
    id: "c2",
    nome: "Ana Sofia",
    telefone: "+258 82 987 6543",
    endereco: "Bairro Central, Matola",
  },
  {
    id: "c3",
    nome: "Carlos Mendes",
    telefone: "+258 86 555 1212",
    endereco: "Costa do Sol, Maputo",
  },
  {
    id: "c4",
    nome: "Fatima dos Santos",
    telefone: "+258 84 777 8899",
    endereco: "Polana Cimento, Maputo",
  },
  {
    id: "c5",
    nome: "João Pedro",
    telefone: "+258 87 222 3344",
    endereco: "Alto Maé, Maputo",
  },
];

export const ingredientes: Ingrediente[] = [
  {
    id: "i1",
    nome: "Farinha",
    quantidadeAtual: 12,
    unidade: "kg",
    precoCompra: 2500,
    quantidadeCompra: 50,
    estoqueMinimo: 5,
  },
  {
    id: "i2",
    nome: "Açúcar",
    quantidadeAtual: 2.5,
    unidade: "kg",
    precoCompra: 1800,
    quantidadeCompra: 25,
    estoqueMinimo: 4,
  },
  {
    id: "i3",
    nome: "Ovos",
    quantidadeAtual: 18,
    unidade: "un",
    precoCompra: 600,
    quantidadeCompra: 30,
    estoqueMinimo: 24,
  },
  {
    id: "i4",
    nome: "Chocolate",
    quantidadeAtual: 1.2,
    unidade: "kg",
    precoCompra: 3200,
    quantidadeCompra: 5,
    estoqueMinimo: 1.5,
  },
  {
    id: "i5",
    nome: "Leite",
    quantidadeAtual: 8,
    unidade: "l",
    precoCompra: 900,
    quantidadeCompra: 12,
    estoqueMinimo: 3,
  },
  {
    id: "i6",
    nome: "Manteiga",
    quantidadeAtual: 3.5,
    unidade: "kg",
    precoCompra: 2800,
    quantidadeCompra: 10,
    estoqueMinimo: 2,
  },
  {
    id: "i7",
    nome: "Cacau em pó",
    quantidadeAtual: 0.8,
    unidade: "kg",
    precoCompra: 1500,
    quantidadeCompra: 2,
    estoqueMinimo: 0.5,
  },
];

export const produtos: Produto[] = [
  {
    id: "p1",
    nome: "Bolo de Chocolate",
    categoria: "Bolos",
    preco: 2500,
    materiaisNecessarios: [
      { materialId: "mat2", quantidade: 1 },
      { materialId: "mat3", quantidade: 0.5 },
    ],
    receita: [
      { ingredienteId: "i1", quantidade: 500, unidade: "g" },
      { ingredienteId: "i2", quantidade: 300, unidade: "g" },
      { ingredienteId: "i3", quantidade: 6, unidade: "un" },
      { ingredienteId: "i5", quantidade: 200, unidade: "ml" },
      { ingredienteId: "i6", quantidade: 100, unidade: "g" },
      { ingredienteId: "i4", quantidade: 200, unidade: "g" },
    ],
    modoPreparo: [
      "Pré-aqueça o forno a 180 °C e unte uma forma redonda.",
      "Derreta o chocolate com a manteiga em banho-maria.",
      "Bata os ovos com o açúcar até dobrar de volume.",
      "Incorpore o chocolate derretido e o leite.",
      "Adicione a farinha peneirada e misture delicadamente.",
      "Asse por 40–45 minutos. Deixe arrefecer antes de desenformar.",
    ],
  },
  {
    id: "p2",
    nome: "Bolo Red Velvet",
    categoria: "Bolos",
    preco: 3200,
    materiaisNecessarios: [
      { materialId: "mat2", quantidade: 1 },
      { materialId: "mat3", quantidade: 0.5 },
    ],
    receita: [
      { ingredienteId: "i1", quantidade: 450, unidade: "g" },
      { ingredienteId: "i2", quantidade: 350, unidade: "g" },
      { ingredienteId: "i3", quantidade: 4, unidade: "un" },
      { ingredienteId: "i5", quantidade: 250, unidade: "ml" },
      { ingredienteId: "i6", quantidade: 150, unidade: "g" },
      { ingredienteId: "i7", quantidade: 40, unidade: "g" },
    ],
    modoPreparo: [
      "Pré-aqueça o forno a 175 °C.",
      "Bata a manteiga com o açúcar até ficar cremoso.",
      "Junte os ovos um a um, depois o leite e o corante vermelho.",
      "Misture a farinha com o cacau e incorpore aos poucos.",
      "Asse por 35 minutos e deixe arrefecer.",
      "Recheie e cubra com creme de queijo.",
    ],
  },
  {
    id: "p3",
    nome: "Brigadeiro",
    categoria: "Doces",
    preco: 50,
    materiaisNecessarios: [
      { materialId: "mat5", quantidade: 0.1 },
    ],
    receita: [
      { ingredienteId: "i4", quantidade: 20, unidade: "g" },
      { ingredienteId: "i6", quantidade: 10, unidade: "g" },
      { ingredienteId: "i5", quantidade: 30, unidade: "ml" },
    ],
    modoPreparo: [
      "Leve ao lume o leite condensado, o chocolate e a manteiga.",
      "Mexa sempre até desprender do fundo da panela.",
      "Deixe arrefecer, enrole em bolinhas e passe no granulado.",
    ],
  },
  {
    id: "p4",
    nome: "Coxinha",
    categoria: "Salgados",
    preco: 45,
    receita: [
      { ingredienteId: "i1", quantidade: 40, unidade: "g" },
      { ingredienteId: "i5", quantidade: 50, unidade: "ml" },
      { ingredienteId: "i6", quantidade: 15, unidade: "g" },
    ],
  },
  {
    id: "p5",
    nome: "Empadas",
    categoria: "Salgados",
    preco: 55,
    receita: [
      { ingredienteId: "i1", quantidade: 50, unidade: "g" },
      { ingredienteId: "i6", quantidade: 25, unidade: "g" },
      { ingredienteId: "i3", quantidade: 1, unidade: "un" },
    ],
  },
  {
    id: "p6",
    nome: "Bolo de Baunilha",
    categoria: "Bolos",
    preco: 2000,
    materiaisNecessarios: [
      { materialId: "mat1", quantidade: 1 },
      { materialId: "mat3", quantidade: 0.5 },
    ],
    receita: [
      { ingredienteId: "i1", quantidade: 450, unidade: "g" },
      { ingredienteId: "i2", quantidade: 280, unidade: "g" },
      { ingredienteId: "i3", quantidade: 5, unidade: "un" },
      { ingredienteId: "i5", quantidade: 200, unidade: "ml" },
      { ingredienteId: "i6", quantidade: 120, unidade: "g" },
    ],
    modoPreparo: [
      "Pré-aqueça o forno a 180 °C.",
      "Bata a manteiga com o açúcar, junte os ovos e a baunilha.",
      "Alterne a farinha e o leite, misturando levemente.",
      "Asse por 35–40 minutos.",
    ],
  },
  {
    id: "p7",
    nome: "Bolo de Aniversário (2 andares)",
    categoria: "Bolos",
    preco: 5500,
    materiaisNecessarios: [
      { materialId: "mat2", quantidade: 1 },
      { materialId: "mat3", quantidade: 1 },
      { materialId: "mat4", quantidade: 5 },
    ],
    receita: [
      { ingredienteId: "i1", quantidade: 1000, unidade: "g" },
      { ingredienteId: "i2", quantidade: 700, unidade: "g" },
      { ingredienteId: "i3", quantidade: 12, unidade: "un" },
      { ingredienteId: "i5", quantidade: 500, unidade: "ml" },
      { ingredienteId: "i6", quantidade: 300, unidade: "g" },
      { ingredienteId: "i4", quantidade: 300, unidade: "g" },
    ],
  },
  {
    id: "p8",
    nome: "Cupcake de Chocolate",
    categoria: "Doces",
    preco: 120,
    receita: [
      { ingredienteId: "i1", quantidade: 30, unidade: "g" },
      { ingredienteId: "i2", quantidade: 25, unidade: "g" },
      { ingredienteId: "i4", quantidade: 15, unidade: "g" },
      { ingredienteId: "i3", quantidade: 1, unidade: "un" },
    ],
  },
  {
    id: "p9",
    nome: "Beijinho",
    categoria: "Doces",
    preco: 50,
    receita: [
      { ingredienteId: "i2", quantidade: 15, unidade: "g" },
      { ingredienteId: "i6", quantidade: 8, unidade: "g" },
      { ingredienteId: "i5", quantidade: 30, unidade: "ml" },
    ],
  },
  {
    id: "p10",
    nome: "Cookies de Chocolate",
    categoria: "Doces",
    preco: 80,
    receita: [
      { ingredienteId: "i1", quantidade: 25, unidade: "g" },
      { ingredienteId: "i2", quantidade: 20, unidade: "g" },
      { ingredienteId: "i6", quantidade: 12, unidade: "g" },
      { ingredienteId: "i4", quantidade: 18, unidade: "g" },
    ],
  },
  {
    id: "p11",
    nome: "Rissóis de Camarão",
    categoria: "Salgados",
    preco: 40,
    receita: [
      { ingredienteId: "i1", quantidade: 35, unidade: "g" },
      { ingredienteId: "i5", quantidade: 40, unidade: "ml" },
      { ingredienteId: "i6", quantidade: 10, unidade: "g" },
    ],
  },
  {
    id: "p12",
    nome: "Pão de Queijo",
    categoria: "Salgados",
    preco: 35,
    receita: [
      { ingredienteId: "i1", quantidade: 30, unidade: "g" },
      { ingredienteId: "i5", quantidade: 25, unidade: "ml" },
      { ingredienteId: "i3", quantidade: 1, unidade: "un" },
    ],
  },
  {
    id: "p13",
    nome: "Mousse de Chocolate",
    categoria: "Sobremesas",
    preco: 350,
    receita: [
      { ingredienteId: "i4", quantidade: 120, unidade: "g" },
      { ingredienteId: "i3", quantidade: 3, unidade: "un" },
      { ingredienteId: "i2", quantidade: 60, unidade: "g" },
      { ingredienteId: "i5", quantidade: 100, unidade: "ml" },
    ],
    modoPreparo: [
      "Derreta o chocolate em banho-maria.",
      "Separe as gemas das claras e bata as claras em castelo.",
      "Misture as gemas e o açúcar ao chocolate.",
      "Envolva as claras delicadamente.",
      "Leve ao frigorífico por pelo menos 4 horas.",
    ],
  },
];

export const pedidos: Pedido[] = [
  {
    id: "ped1",
    clienteId: "c1",
    itens: [
      { produtoId: "p1", quantidade: 1 },
      { produtoId: "p3", quantidade: 20 },
    ],
    dataEntrega: "2026-07-20",
    hora: "15:00",
    valor: 3500,
    pago: 3500,
    estado: "em_producao",
    criadoEm: "2026-07-18",
  },
  {
    id: "ped2",
    clienteId: "c2",
    itens: [{ produtoId: "p2", quantidade: 1 }],
    dataEntrega: "2026-07-20",
    hora: "18:30",
    valor: 3200,
    pago: 1500,
    estado: "pendente",
    criadoEm: "2026-07-19",
  },
  {
    id: "ped3",
    clienteId: "c4",
    itens: [
      { produtoId: "p1", quantidade: 2 },
      { produtoId: "p4", quantidade: 30 },
    ],
    dataEntrega: "2026-07-21",
    hora: "10:00",
    valor: 6350,
    pago: 3000,
    estado: "pendente",
    criadoEm: "2026-07-17",
  },
  {
    id: "ped4",
    clienteId: "c3",
    itens: [
      { produtoId: "p2", quantidade: 1 },
      { produtoId: "p5", quantidade: 40 },
    ],
    dataEntrega: "2026-07-22",
    hora: "16:00",
    valor: 5400,
    pago: 5400,
    estado: "pronto",
    criadoEm: "2026-07-15",
  },
  {
    id: "ped5",
    clienteId: "c1",
    itens: [{ produtoId: "p1", quantidade: 3 }],
    dataEntrega: "2026-07-25",
    hora: "14:00",
    valor: 7500,
    pago: 0,
    estado: "pendente",
    criadoEm: "2026-07-19",
  },
  {
    id: "ped6",
    clienteId: "c5",
    itens: [
      { produtoId: "p4", quantidade: 50 },
      { produtoId: "p5", quantidade: 50 },
    ],
    dataEntrega: "2026-07-18",
    hora: "12:00",
    valor: 5000,
    pago: 5000,
    estado: "entregue",
    criadoEm: "2026-07-10",
  },
  {
    id: "ped7",
    clienteId: "c1",
    itens: [{ produtoId: "p2", quantidade: 1 }],
    dataEntrega: "2026-07-12",
    hora: "11:00",
    valor: 3200,
    pago: 3200,
    estado: "entregue",
    criadoEm: "2026-07-08",
  },
  {
    id: "ped8",
    clienteId: "c2",
    itens: [{ produtoId: "p3", quantidade: 100 }],
    dataEntrega: "2026-07-23",
    hora: "09:00",
    valor: 5000,
    pago: 2000,
    estado: "pendente",
    criadoEm: "2026-07-20",
  },
  {
    id: "ped9",
    clienteId: "c4",
    itens: [{ produtoId: "p1", quantidade: 1 }],
    dataEntrega: "2026-07-26",
    hora: "17:00",
    valor: 10000,
    pago: 4000,
    estado: "em_producao",
    criadoEm: "2026-07-16",
  },
  {
    id: "ped10",
    clienteId: "c3",
    itens: [{ produtoId: "p5", quantidade: 20 }],
    dataEntrega: "2026-07-19",
    hora: "13:00",
    valor: 1100,
    pago: 1100,
    estado: "cancelado",
    criadoEm: "2026-07-14",
  },
];

export const movimentosCaixa: MovimentoCaixa[] = [
  // Fevereiro
  { id: "m20", tipo: "entrada", descricao: "Vendas — fevereiro", valor: 18500, data: "2026-02-28", categoria: "Venda" },
  { id: "m21", tipo: "saida", descricao: "Ingredientes — fevereiro", valor: 6200, data: "2026-02-20", categoria: "Ingredientes" },
  { id: "m22", tipo: "saida", descricao: "Utilidades — fevereiro", valor: 3100, data: "2026-02-25", categoria: "Utilidades" },
  // Março
  { id: "m23", tipo: "entrada", descricao: "Vendas — março", valor: 22100, data: "2026-03-28", categoria: "Venda" },
  { id: "m24", tipo: "saida", descricao: "Ingredientes — março", valor: 7400, data: "2026-03-18", categoria: "Ingredientes" },
  { id: "m25", tipo: "saida", descricao: "Utilidades — março", valor: 2900, data: "2026-03-22", categoria: "Utilidades" },
  { id: "m26", tipo: "saida", descricao: "Transporte — março", valor: 1100, data: "2026-03-27", categoria: "Transporte" },
  // Abril
  { id: "m27", tipo: "entrada", descricao: "Vendas — abril", valor: 19800, data: "2026-04-27", categoria: "Venda" },
  { id: "m28", tipo: "saida", descricao: "Ingredientes — abril", valor: 6800, data: "2026-04-15", categoria: "Ingredientes" },
  { id: "m29", tipo: "saida", descricao: "Utilidades — abril", valor: 3400, data: "2026-04-20", categoria: "Utilidades" },
  // Maio
  { id: "m30", tipo: "entrada", descricao: "Vendas — maio", valor: 25600, data: "2026-05-29", categoria: "Venda" },
  { id: "m31", tipo: "saida", descricao: "Ingredientes — maio", valor: 8100, data: "2026-05-14", categoria: "Ingredientes" },
  { id: "m32", tipo: "saida", descricao: "Utilidades — maio", valor: 3000, data: "2026-05-21", categoria: "Utilidades" },
  { id: "m33", tipo: "saida", descricao: "Transporte — maio", valor: 1400, data: "2026-05-26", categoria: "Transporte" },
  // Junho
  { id: "m34", tipo: "entrada", descricao: "Vendas — junho", valor: 24300, data: "2026-06-28", categoria: "Venda" },
  { id: "m35", tipo: "saida", descricao: "Ingredientes — junho", valor: 7900, data: "2026-06-12", categoria: "Ingredientes" },
  { id: "m36", tipo: "saida", descricao: "Utilidades — junho", valor: 3200, data: "2026-06-18", categoria: "Utilidades" },
  { id: "m37", tipo: "saida", descricao: "Transporte — junho", valor: 1200, data: "2026-06-24", categoria: "Transporte" },
  // Julho (mês atual)
  { id: "m1", tipo: "entrada", descricao: "Venda — pedido ped6", valor: 5000, data: "2026-07-18", categoria: "Venda" },
  { id: "m2", tipo: "entrada", descricao: "Venda — pedido ped7", valor: 3200, data: "2026-07-12", categoria: "Venda" },
  { id: "m3", tipo: "entrada", descricao: "Sinal — pedido ped2", valor: 1500, data: "2026-07-19", categoria: "Venda" },
  { id: "m4", tipo: "saida", descricao: "Compra de ovos", valor: 600, data: "2026-07-10", categoria: "Ingredientes" },
  { id: "m5", tipo: "saida", descricao: "Compra de farinha", valor: 2500, data: "2026-07-05", categoria: "Ingredientes" },
  { id: "m6", tipo: "saida", descricao: "Gás", valor: 1200, data: "2026-07-08", categoria: "Utilidades" },
  { id: "m7", tipo: "saida", descricao: "Energia", valor: 2800, data: "2026-07-15", categoria: "Utilidades" },
  { id: "m8", tipo: "saida", descricao: "Transporte de entregas", valor: 900, data: "2026-07-18", categoria: "Transporte" },
  { id: "m9", tipo: "entrada", descricao: "Sinal — pedido ped9", valor: 4000, data: "2026-07-16", categoria: "Venda" },
  { id: "m10", tipo: "saida", descricao: "Compra de chocolate", valor: 3200, data: "2026-07-11", categoria: "Ingredientes" },
];

export const contasPagar: ContaPagar[] = [
  {
    id: "cp1",
    fornecedor: "Fornecedor de farinha",
    descricao: "Saco 50kg",
    valor: 4500,
    vencimento: "2026-07-25",
    paga: false,
  },
  {
    id: "cp2",
    fornecedor: "Lacticínios Maputo",
    descricao: "Leite e manteiga",
    valor: 2800,
    vencimento: "2026-07-22",
    paga: false,
  },
  {
    id: "cp3",
    fornecedor: "EDM",
    descricao: "Energia — julho",
    valor: 2800,
    vencimento: "2026-07-28",
    paga: false,
  },
  {
    id: "cp4",
    fornecedor: "Mercado do peixe",
    descricao: "Ovos (lote anterior)",
    valor: 600,
    vencimento: "2026-07-12",
    paga: true,
  },
];

export const eventos: EventoCalendario[] = [
  { id: "e1", titulo: "Entrega Maria José", data: "2026-07-20", hora: "15:00", tipo: "pedido", pedidoId: "ped1" },
  { id: "e2", titulo: "Entrega Ana Sofia", data: "2026-07-20", hora: "18:30", tipo: "pedido", pedidoId: "ped2" },
  { id: "e3", titulo: "Casamento — família Mendes", data: "2026-07-22", hora: "16:00", tipo: "casamento", pedidoId: "ped4" },
  { id: "e4", titulo: "Festa infantil — Fatima", data: "2026-07-21", hora: "10:00", tipo: "festa", pedidoId: "ped3" },
  { id: "e5", titulo: "Aniversário Fatima dos Santos", data: "2026-07-25", tipo: "aniversario" },
  { id: "e6", titulo: "3 bolos chocolate — Maria José", data: "2026-07-25", hora: "14:00", tipo: "pedido", pedidoId: "ped5" },
  { id: "e7", titulo: "Brigadeiros — Ana Sofia", data: "2026-07-23", hora: "09:00", tipo: "pedido", pedidoId: "ped8" },
  { id: "e8", titulo: "Aniversário Ana Sofia", data: "2026-07-22", tipo: "aniversario" },
];

export const materiais: Material[] = [
  { id: "mat1", nome: "Caixa de bolo P", categoria: "Embalagem", quantidade: 15, unidade: "un", precoUnitario: 25, estoqueMinimo: 5 },
  { id: "mat2", nome: "Caixa de bolo G", categoria: "Embalagem", quantidade: 8, unidade: "un", precoUnitario: 45, estoqueMinimo: 3 },
  { id: "mat3", nome: "Fita decorativa", categoria: "Decoração", quantidade: 3, unidade: "rolo", precoUnitario: 80, estoqueMinimo: 1 },
  { id: "mat4", nome: "Velas coloridas", categoria: "Decoração", quantidade: 24, unidade: "un", precoUnitario: 5, estoqueMinimo: 10 },
  { id: "mat5", nome: "Saco de embalagem", categoria: "Embalagem", quantidade: 50, unidade: "un", precoUnitario: 8, estoqueMinimo: 20 },
  { id: "mat6", nome: "Papel de seda", categoria: "Embalagem", quantidade: 1, unidade: "pacote", precoUnitario: 35, estoqueMinimo: 2 },
];

export const perdas: Perda[] = [
  { id: "per1", tipo: "ingrediente", ingredienteId: "i3", quantidade: 3,   motivo: "Ovos partidos",      data: "2026-07-18" },
  { id: "per2", tipo: "ingrediente", ingredienteId: "i2", quantidade: 0.2, motivo: "Calda que sobrou",   data: "2026-07-17" },
  { id: "per3", tipo: "ingrediente", ingredienteId: "i4", quantidade: 0.1, motivo: "Receita de teste",   data: "2026-07-15" },
  { id: "per4", tipo: "ingrediente", ingredienteId: "i1", quantidade: 0.5, motivo: "Erro de preparo",    data: "2026-07-12" },
];

/** Histórico fictício de gasto por cliente (além dos pedidos listados) */
export const gastoHistoricoExtra: Record<string, { pedidos: number; gasto: number }> = {
  c1: { pedidos: 9, gasto: 72300 },
  c2: { pedidos: 4, gasto: 18200 },
  c3: { pedidos: 3, gasto: 14500 },
  c4: { pedidos: 5, gasto: 28900 },
  c5: { pedidos: 2, gasto: 8200 },
};
